name: touchless_elevator
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  flutter_timer: ^0.0.6
  font_awesome_flutter: ^8.8.1
  qr_code_scanner: ^0.0.13
  animated_text_kit: ^2.2.0
  mqtt_client: ^5.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family:  ButtonIcons
      fonts:
        - asset: fonts/ButtonIcons.ttf